#!/bin/bash

# mount_media
#
# When more than one diskful install is configured in 'targets', which media
# should be mounted at any given time is ambiguous. This script ensures that
# the media specified for the given target is available for a diskful install.
#
# Usage:
# mount_media <target>
#
# where target is one of the files in the 'target' subdirectory of sunboot.

[[ $EUID -ne 0 ]] && { echo "This script must be run as root"; exit 1; }

source /vagrant/scripts/functions.sh
target_file="/vagrant/targets/$1"

[[ ! -f "$target_file" ]] && error_exit "Target \"$1\" not found."

source "$target_file"

case $INSTALLMEDIA in
    CDROM) cdrom_mount ;;
    TAPE) error_exit "Not yet supported" ;;
esac
